/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{ts,tsx,js,jsx}",
    "./components/**/*.{ts,tsx,js,jsx}",
    "./pages/**/*.{ts,tsx,js,jsx}",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {},
  },
  safelist: [
    { pattern: /^text-/ },
    { pattern: /^px-/ },
    { pattern: /^py-/ },
    { pattern: /^p[trblxy]-/ },
    { pattern: /^bg-/ },
    { pattern: /^border-/ },
    { pattern: /^rounded-/ },
    { pattern: /^shadow/ },
    { pattern: /^min-w-/ },
    { pattern: /^h-/ },
    { pattern: /^w-/ },
    { pattern: /^font-/ },
    { pattern: /^leading-/ },
    { pattern: /^duration-/ },
    { pattern: /^(sm|md|lg|xl):/ },
    { pattern: /^(hover|focus|active):/ },
    { pattern: /^flex/ },
    { pattern: /^items-/ },
    { pattern: /^justify-/ },
    { pattern: /^gap-/ },
    { pattern: /^max-/ },
    { pattern: /^list-/ },
    { pattern: /^animate-/ },
    { pattern: /^text-\[/ },
    { pattern: /^bg-\[/ },
  ],
  plugins: [],
};
